/**
 * Everything in this file is a sample measure of what would be generated by Muse
 * They're temporary dummies to test and play around with
 *
 * Each variable is an array that represents a measure
 * They should all have 8 elements, 
 * as each element corresponds with an eighth note count
 *
 * Each element is an array of notes played on the index-th count
 *
 * Each note contains three elements, in the form of:
 *     [note number, velocity, note length]
 *     - note number is the midi note value for midi sequences 
 *       or between 0 and 4 for the drumset representing different parts of the set
 *     - velocity is the intensity of the soundhow loud it is
 *     - note length is the duration of the note, represented in standard musical notation
 *         - i.e. a value of 0.25 refers to a quarter note
 */

const LEAD = [
  [[60, 100, 0.25]], 
  [[]],
  [[62, 100, 0.125]],
  [[64, 100, 0.125]],
  [[65, 100, 0.5]],
  [[]],
  [[]],
  [[]]
]

const CHORD_1 = [
  [[48, 20, 4], [52, 20, 4], [55, 20, 4]], 
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]]
]

const CHORD_2 = [
  [[43, 20, 4], [47, 20, 4], [50, 20, 4]], 
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]]
]

const CHORD_3 = [
  [[45, 20, 4], [48, 20, 4], [52, 20, 4]], 
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]]
]

const CHORD_4 = [
  [[41, 20, 4], [45, 20, 4], [48, 20, 4]], 
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]],
  [[]]
]

/**
 * note number values: 
 * 
 * 0 - bassDrum
 * 1 - hiHatClosed
 * 2 - hiHatOpen
 * 3 - snare
 * 4 - ride
 *
 * Intentionally indented in this way 
 * for me to better understand the notes in this beat
 */
const DRUMS = [
  [[0, 80, 0.25], [1, 80, 0.25]],
  [               [1, 80, 0.25]],
  [               [1, 80, 0.25],              [3, 80, 0.25]],
  [               [1, 80, 0.25]],
  [               [1, 80, 0.25]],
  [[0, 80, 0.25], [1, 80, 0.25]],
  [               [1, 80, 0.25],               [3, 80, 0.25]],
  [                              [2, 80, 0.25]] 
]

export default { LEAD, CHORD_1, CHORD_2, CHORD_3, CHORD_4, DRUMS }
